# Generated by Django 4.2.5 on 2023-10-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('discounted_price', models.FloatField()),
                ('selling_price', models.FloatField()),
                ('category', models.CharField(choices=[('ST', 'Shirts'), ('PT', 'Pants'), ('TS', 'Tshirts'), ('TR', 'Tracks'), ('SR', 'Shorts'), ('WT', 'Watches'), ('SE', 'Shoes')], max_length=2)),
                ('image', models.ImageField(upload_to='Static/images')),
            ],
        ),
    ]
